name: Build unsigned iOS IPA

on:
  push: {branches: [main]}
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
    # … all your existing build steps …
    - uses: actions/upload-artifact@v4
      with:
        name: ios-dsym
        path: Export/ios/build/Release-iphoneos/**/*.dSYM
    - uses: actions/upload-artifact@v4
      with:
        name: unsigned-ipa
        path: unsigned.ipa

  symbolicate:
    needs: build                 # ← waits for build job
    runs-on: macos-13
    if: ${{ github.ref == 'refs/heads/main' }}  # run only on main
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4       # now same run ⇒ simple
      with:
        name: ios-dsym
        path: dsym
    - name: Locate crash log
      id: findlog
      run: |
        CRASH=$(ls crashlogs/*.{ips,crash} 2>/dev/null | head -n1)
        if [ -z "$CRASH" ]; then
          echo "No crash log in crashlogs/"; exit 1
        fi
        echo "crash=$CRASH" >> $GITHUB_OUTPUT
    - name: Symbolicate
      run: |
        symbolicatecrash "${{ steps.findlog.outputs.crash }}" \
                         "$(find dsym -name '*.dSYM' -maxdepth 2 | head -n1)" \
                         > crash.symbolicated
    - uses: actions/upload-artifact@v4
      with:
        name: symbolicated-crash
        path: crash.symbolicated
